# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9535a92d99ed6e6cc296e5f104116bb2a14133a8f9c4183ee26faea535b4161185b0d444fe4b7861946b576e6d38cb7e894b1a2e4ab837d47ec456832d74ece

test:
  secret_key_base: 997369e489d6e01b0cbe8fef2a2bfe0b0d15484c605821f214a50226858df5dcb868cb38a101d5c626889a5d12a198e6b2e38e65955073644116f6ae90b2f0df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
